"""Build metadata — embedded in the executable at build time.

This module is auto-generated by the CI pipeline before PyInstaller builds.
Values are injected via environment variables or left as defaults for local builds.
"""

import os
from datetime import datetime, timezone

# Version is always read from VERSION file (single source of truth)
_VERSION_FILE = os.path.join(os.path.dirname(__file__), "..", "..", "..", "VERSION")


def _read_version() -> str:
    try:
        with open(_VERSION_FILE, encoding="utf-8") as f:
            return f.read().strip()
    except FileNotFoundError:
        return "0.0.0-dev"


VERSION = os.environ.get("APP_VERSION", _read_version())
BUILD_DATE = os.environ.get("BUILD_DATE", datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
GIT_COMMIT = os.environ.get("GIT_COMMIT", "unknown")
GIT_BRANCH = os.environ.get("GIT_BRANCH", "unknown")
BUILD_NUMBER = os.environ.get("BUILD_NUMBER", "0")
PYTHON_VERSION = os.environ.get("PYTHON_VERSION", f"{__import__('sys').version_info.major}.{__import__('sys').version_info.minor}.{__import__('sys').version_info.micro}")
BUILD_TYPE = os.environ.get("BUILD_TYPE", "local")


def get_build_info() -> dict:
    """Return build metadata as a dictionary."""
    return {
        "version": VERSION,
        "build_date": BUILD_DATE,
        "git_commit": GIT_COMMIT,
        "git_branch": GIT_BRANCH,
        "build_number": BUILD_NUMBER,
        "python_version": PYTHON_VERSION,
        "build_type": BUILD_TYPE,
    }


def get_version_string() -> str:
    """Return a human-readable version string."""
    return f"{VERSION} (build {BUILD_NUMBER}, {GIT_COMMIT[:8]})"


__all__ = ["VERSION", "BUILD_DATE", "GIT_COMMIT", "GIT_BRANCH", "BUILD_NUMBER",
           "PYTHON_VERSION", "BUILD_TYPE", "get_build_info", "get_version_string"]
